---

- name: Facts | Debug zones
  ansible.builtin.debug:
    var: firewalld_zones | default(Omit)
    verbosity: 2

- name: Facts | retrieve current machine ip
  ansible.builtin.setup:
    gather_subset:
      - all_ipv4_addresses
  register: current_network_facts
  delegate_facts: true

- name: Facts | Debug network facts
  ansible.builtin.debug:
    var: current_network_facts
    verbosity: 2
