---

- name: Port-forwarding | Redirect port
  become: "{{ firewalld_become }}"
  ansible.posix.firewalld:
    rich_rule: >
      rule family={{ forward_rule.family | default('ipv4') }}
      forward-port port={{ forward_rule.from_port | int }}
      protocol={{ forward_rule.protocol | default('tcp') }}
      to-port={{ forward_rule.to_port | int }}
      log prefix={{ forward_rule.port_forward_rule }}
    zone: "{{ zone.name | default(firewalld_default_zone) }}"
    permanent: yes
    immediate: yes
    state: enabled
  when:
   - not forward_rule.to_address is defined
   - not forward_rule.to_host is defined
   - not forward_rule.to_ansible_host is defined

- name: Port-forwarding | forward rule to host is defined # should be duplicated because delegate_to is evaluated before when clause
  ansible.builtin.include_tasks: port-forwarding-to-host.yml
  when: forward_rule.to_host is defined or foward_rule.to_ansible_host is defined

- name: Port-forwarding | compute redirect ip
  ansible.builtin.debug:
    msg: "{{ forward_rule.to_address }}"
  register: forwardrule_address
  when: forward_rule.to_address is defined

- name: Port-forwarding | Redirect ip
  become: "{{ firewalld_become }}"
  ansible.posix.firewalld:
    rich_rule: >
      rule family={{ forward_rule.family | default('ipv4') }}
      forward-port port={{ forward_rule.from_port | int }}
      protocol={{ forward_rule.protocol | default('tcp') }}
      to-addr={{ forwardrule_address.msg | ansible.utils.ipaddr }}
      to-port={{ forward_rule.to_port | int }}
      log prefix={{ forward_rule.port_forward_rule }}
    zone: "{{ zone.name | default(firewalld_default_zone) }}"
    permanent: yes
    immediate: yes
    state: enabled
  when: forward_rule.to_address is defined
