---

- name: Activate prerequisite kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - "br_netfilter"
    - "nf_conntrack"
  become: true
  ignore_errors: true
  register: modprobe_result
  when: ansible_env.CI is not defined

- name: Check if br_netfilter module is loaded
  ansible.builtin.command: lsmod
  become: true
  changed_when: false
  register: lsmod_result
  when: ansible_env.CI is not defined

- name: Permanently allow ipv4 traffic forwarding on host nic
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: false
  become: yes
  when: ansible_env.CI is not defined

- name: Permanently allow ipv6 traffic forwarding on host nic
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '0'
    sysctl_set: true
    state: present
    reload: false
  become: yes
  when: ansible_env.CI is not defined

- name: Activate bridge nf
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: true
    state: present
    reload: "{{ ansible_env.CI is not defined }}"
  become: true
  when:
    - ansible_env.CI is not defined
    - "'br_netfilter' in (lsmod_result.stdout | default(''))"

- name: Activate bridge-nf-call-ip6tables
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_set: true
    state: present
    reload: "{{ ansible_env.CI is not defined }}"
  become: true
  when:
    - ansible_env.CI is not defined
    - "'br_netfilter' in (lsmod_result.stdout | default(''))"

- name: Activate bridge-nf-call-arptables
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-arptables
    value: '0'
    sysctl_set: true
    state: present
    reload: "{{ ansible_env.CI is not defined }}"
  become: true
  when:
    - ansible_env.CI is not defined
    - "'br_netfilter' in (lsmod_result.stdout | default(''))"

- name: Increase conntrack max
  ansible.posix.sysctl:
    name: net.netfilter.nf_conntrack_max
    value: '1000000'
    sysctl_set: true
    state: present
    reload: "{{ ansible_env.CI is not defined }}"
  become: true
  when: ansible_env.CI is not defined
