{% if item.registry is defined %}
	FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
	FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
	{% for var, value in item.env.items() %}
		{% if value %}
ENV {{ var }} {{ value }}
		{% endif %}
	{% endfor %}
{% endif %}
# Tweak firewalld configuration to work in a container and be close to real machines

RUN dnf -y install \
      systemd \
      python3 \
      firewalld \
      iptables \
      iptables-nft \
      dbus \
      dbus-daemon \
      polkit \
      NetworkManager \
      iproute \
      hostname && \
    dnf clean all && \
    # Force iptables backend: nftables doesn't work inside unprivileged containers
    sed -i 's/FirewallBackend=nftables/FirewallBackend=iptables/g' /etc/firewalld/firewalld.conf && \
    sed -i 's/IndividualCalls=no/IndividualCalls=yes/g' /etc/firewalld/firewalld.conf && \
    # firewalld hardening uses mount namespace operations blocked in rootless containers
    mkdir -p /etc/systemd/system/firewalld.service.d && \
    printf '%s\n' '[Service]' 'ProtectHostname=no' 'ProtectControlGroups=no' > /etc/systemd/system/firewalld.service.d/10-container-compat.conf && \
    # Mask units that are truly incompatible with containers (hardware/host-ns dependent)
    systemctl mask \
      dev-hugepages.mount \
      sys-fs-fuse-connections.mount \
      systemd-hwdb-update.service \
      systemd-update-utmp.service \
      systemd-update-utmp-runlevel.service \
      getty.target \
      console-getty.service && \
    # Remove udev socket triggers that need a real host (cause boot hangs in container)
    rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*
{% if item.command is defined %}
CMD ["{{ item.command }}"]
{% endif %}
