{% if item.registry is defined %}
	FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
	FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
	{% for var, value in item.env.items() %}
		{% if value %}
ENV {{ var }} {{ value }}
		{% endif %}
	{% endfor %}
{% endif %}
{% if item.volumes is defined %}
VOLUME ["/sys/fs/cgroup"]
{% endif %}
RUN dnf -y install systemd python3 python3-libdnf5 procps-ng && \
    dnf clean all && \
    mkdir -p /var/tmp/ansible-remote && \
    chmod 1777 /var/tmp/ansible-remote && \
    (cd /lib/systemd/system/sysinit.target.wants/ ; for i in * ; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i ; done) && \
    rm -f /lib/systemd/system/multi-user.target.wants/* && \
    rm -f /etc/systemd/system/*.wants/* && \
    rm -f /lib/systemd/system/local-fs.target.wants/* && \
    rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl* && \
    rm -f /lib/systemd/system/basic.target.wants/* && \
    rm -f /lib/systemd/system/anaconda.target.wants/* && \
    ln -sf /dev/null /etc/systemd/system/NetworkManager.service && \
    ln -sf /dev/null /etc/systemd/system/systemd-networkd.service && \
    ln -sf /dev/null /etc/systemd/system/systemd-resolved.service && \
    ln -sf /dev/null /etc/systemd/system/systemd-networkd.socket && \
    ln -sf /dev/null /etc/systemd/system/NetworkManager-wait-online.service && \
    ln -sf /dev/null /etc/systemd/system/network-online.target{% if item.command is defined %}
CMD ["{{ item.command }}"]
{% endif %}
