---
# handlers file for ansible-routing

- name: Handler | reload-firewall
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  become: yes
  listen: ansible-routing | handler | reload-firewall

- name: Handler | restart-firewall
  ansible.builtin.service:
    name: firewalld
    state: restarted
  become: yes
  listen: ansible-routing | restart | restart-firewall
