---
- name: Converge
  hosts: all
  vars:
    preferred_nic: "lo"
    firewalld_zones:
      - name: public
#        nics:
#          - eth0
#        masquerade: true
        port_forward_rules:
          - port_forward_rule: ssh-to-guest
            family: ipv4
            from_port: 6752
            protocol: tcp
            to_address: 192.168.1.10
            to_port: 22
          - port_forward_rule: host-forwarding
            family: ipv4
            from_port: 6755
            protocol: tcp
            to_host: "proxy.osgiliath.test"
            to_port: 22
        enabled_services:
          - service: ssh
        enabled_sources:
          - source: "192.168.1.10/16"
        enabled_ports:
          - port: 6753
            protocol: tcp
  roles:
    - role: tcharl.ansible_routing
