---
dependency:
  name: galaxy
  enabled: ${DEPENDENCY_ENABLED:-True}
  options:
    role-file: ${REQUIREMENTS_PATH:-requirements.yml}
    requirements-file: requirements-collections.yml
driver:
  name: podman
platforms:
  - name: routing.osgiliath.test
    image: fedora:44
    # image: ubi9/ubi-init:latest
    dockerfile: ../common/Dockerfile.j2
    # registry:
    #   url: registry.access.redhat.com
    privileged: false  # Rootless Podman is already 'safe', privileged often breaks CI namespaces
    command: "/sbin/init"
    #systemd: True  #<-- This is often redundant if using a systemd-ready image or command
    tmpfs:
      /run: rw,size=256m
      /run/lock: rw,size=64m
      /tmp: rw,size=512m
    capabilities:
      - SYS_ADMIN # Gives systemd what it needs without full 'privileged' mode
      - NET_ADMIN
      - NET_RAW
      - MKNOD
    cgroupns_mode: private # 'host' usually fails in rootless CI
    dns_servers:
      - 8.8.8.8
#    capabilities:
#      - SYS_ADMIN
#      - CAP_SYS_TIME
    # pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
