---

- name: Services-ports | enable services
  become: "{{ firewalld_become }}"
  ansible.posix.firewalld:
    zone: "{{ zone.name | default(firewalld_default_zone) }}"
    permanent: true
    immediate: true
    service: "{{ enabled_service.service }}"
    state: enabled
  loop: "{{ zone.enabled_services | default([]) }}"
  loop_control:
    loop_var: enabled_service

- name: Services-ports | add sources
  ansible.posix.firewalld:
    zone: "{{ zone.name | default(firewalld_default_zone) }}"
    permanent: true
    immediate: true
    source: "{{ enabled_source.source }}"
    state: enabled
  become: "{{ firewalld_become }}"
  loop: "{{ zone.enabled_sources | default([]) }}"
  loop_control:
    loop_var: enabled_source

- name: Services-ports | open port
  ansible.posix.firewalld:
    port: "{{ enabled_port.port }}/{{ enabled_port.protocol | default('tcp') }}"
    zone: "{{ zone.name | default(firewalld_default_zone) }}"
    permanent: true
    immediate: true
    state: enabled
  become: "{{ firewalld_become }}"
  loop: "{{ zone.enabled_ports | default([]) }}"
  loop_control:
    loop_var: enabled_port

- name: Services-ports | open port
  ansible.posix.firewalld:
    port: "{{ enabled_port_range.port_range }}/{{ enabled_port.protocol | default('tcp') }}"
    zone: "{{ zone.name | default(firewalld_default_zone) }}"
    permanent: true
    immediate: true
    state: enabled
  become: "{{ firewalld_become }}"
  loop: "{{ zone.enabled_port_ranges | default([]) }}"
  loop_control:
    loop_var: enabled_port_range
